---
title: "R Notebook"
output: html_notebook
---

```{r}
library(plyr)
library(tidyverse)
library(readxl)
```


```{r, warning=FALSE}
rowCount <- 125
colCount <- 64

df <- data.frame(matrix(NA, nrow=(rowCount + 2), ncol=(colCount + 2)))

df[c(1,nrow(df)),] <- "x"
df[,c(1,ncol(df))] <- "x"

colors <- c("r", "o", "y", "g", "b", "i", "v")
squaresRemaining <- rep(rowCount * colCount, 7)

maxSize <- floor(sqrt(ncol(df)) - 1)
fullFlag <- FALSE

sameCounter <- 0
sameCheck <- squaresRemaining

rowFlip <- TRUE

while(!fullFlag) {
  if(rowFlip) {
    rowSeq <- 2:(nrow(df)-1)
    colSeq <- 2:(ncol(df)-1)
    rowFlip <- FALSE
  }
  else {
    rowSeq <- (nrow(df)-1):2
    colSeq <- (ncol(df)-1):2
    rowFlip <- TRUE
  }
  for(r in rowSeq) {
    for(c in colSeq) {
      
      if(is.na(df[r,c])) {
      validFlag <- FALSE
      
      boxSize <- floor(runif(1, min = 0, max = maxSize))
      colorNum <- floor(runif(1, min = 1, max = length(colors) + 1))
      color <- colors[colorNum]
        
      leftover <- squaresRemaining[colorNum] - ((boxSize + 1) * (boxSize + 1))
      
      if((r + boxSize) <= (nrow(df) - 1) & (c + boxSize) <= (ncol(df) - 1) & leftover >= 0) {
        
        temp <- as.data.frame(df[(r-1):(r+boxSize+1), (c-1):(c+boxSize+1)])
        temp[2:(nrow(temp)-1),2:(ncol(temp)-1)] <- NA
        temp[temp == "x"] <- NA
        if(nrow(temp) == 1)
          temp[1,1] <- NA
        else
          temp[c(1,nrow(temp)), c(1,ncol(temp))] <- NA
        
        if(!(FALSE %in% is.na(as.data.frame(df[r:(r+boxSize), c:(c+boxSize)]))) & !is.element(color, unlist(temp))) {
            validFlag <- TRUE
            squaresRemaining[colorNum] <- leftover
            for(br in 0:boxSize)
              for(bc in 0:boxSize)
                df[r + br, c + bc] <- color
        }
      }
        
      if(!is.na(squaresRemaining[colorNum]) & squaresRemaining[colorNum] <= 6000) {
        colors <- colors[-colorNum]
        squaresRemaining <- squaresRemaining[-colorNum]
      }
      
      }
      
    }
  }
  
  if(length(colors) == 1 | sameCounter == 25)
    df[is.na(df)] <- "w"
  
  if(!(TRUE %in% is.na(df)))
    fullFlag <- TRUE
  
  if(sameCheck == squaresRemaining)
    sameCounter <- sameCounter + 1
  else {
    sameCheck <- squaresRemaining
    sameCounter <- 0
  }

}

write.table(df, "../AoC Homemade/input.csv", col.names = FALSE, row.names = FALSE, sep = ",")
```

