---
title: "R Notebook"
output: html_notebook
---

```{r}
df <- read.csv("../Quilting/input.csv", colClasses = rep("character", 10), header = FALSE)
df
```

```{r, warning=FALSE}
red <- c()
orange <- c()
yellow <- c()
green <- c()
blue <- c()
indigo <- c()
violet <- c()

colors <- c("r", "o", "y", "g", "b", "i", "v")
colorCount <- rep(0, 7)

boxSize <- 0

oldColor <- "z"

for(r in 2:(nrow(df) - 1)) {
  for(c in 2:(ncol(df) - 1)) {
    currentColor <- df[r, c]
    if(!is.na(currentColor)) {
      for(place in c:(ncol(df) - 1)) {
        if(!is.na(df[r, place]) & currentColor == df[r, place]) {
          boxSize <- boxSize + 1
        }
        else
          break
      }
      
      testColor <- as.data.frame(df[(r):(r + boxSize), c:(c + boxSize)])[1, 1]
      if (testColor == "r")
        red <- append(red, boxSize)
      if (testColor == "o")
        orange <- append(orange, boxSize)
      if (testColor == "y")
        yellow <- append(yellow, boxSize)
      if (testColor == "g")
        green <- append(green, boxSize)
      if (testColor == "b")
        blue <- append(blue, boxSize)
      if (testColor == "i")
        indigo <- append(indigo, boxSize)
      if (testColor == "v")
        violet <- append(violet, boxSize)
      
      boxSize <- boxSize - 1
      
      colorCount[match(df[r, c], colors)] <- colorCount[match(df[r, c], colors)] + 1
      df[(r):(r + boxSize), c:(c + boxSize)] <- NA
      boxSize <- 0
      oldColor <- currentColor
    }
    
  }
}

colorList <- list(red, orange, yellow, green, blue, indigo, violet)
```

```{r}
newList <- list()
for (i in 1:length(colorList))
  newList <- append(newList, list(sort(as.vector(colorList[[i]][]), decreasing = TRUE)))
colorList <- newList

width <- floor(ncol(df) * .625)
redDF <- data.frame(matrix(NA, nrow = sum(red), ncol = width))
orangeDF <- data.frame(matrix(NA, nrow = sum(orange), ncol = width))
yellowDF <- data.frame(matrix(NA, nrow = sum(yellow), ncol = width))
greenDF <- data.frame(matrix(NA, nrow = sum(green), ncol = width))
blueDF <- data.frame(matrix(NA, nrow = sum(blue), ncol = width))
indigoDF <- data.frame(matrix(NA, nrow = sum(indigo), ncol = width))
violetDF <- data.frame(matrix(NA, nrow = sum(violet), ncol = width))

part2 <- function(xdf, xcolorList) {
  for (i in 1:length(xcolorList)) {
    breakFlag <- FALSE
    boxSize <- as.numeric(unlist(xcolorList)[i]) - 1
    
    #iterate over cells one by one, fill block as they come, reverse of part 1, kinda
    for (r in 1:nrow(xdf)) {
      for (c in 1:ncol(xdf)) {
        maxR <- r + boxSize
        maxC <- c + boxSize
        if (is.na(xdf[r, c]) & maxR <= nrow(xdf) & maxC <= ncol(xdf)) {
          xdf[r:(r + boxSize), c:(c + boxSize)] <- (boxSize + 1)
          breakFlag <- TRUE
          break
        }
      }
      if (breakFlag)
        break
    }
  }
  return(xdf)
}

redDF <- part2(redDF, colorList[[1]][])
redDF
orangeDF <- part2(orangeDF, colorList[[2]][])
yellowDF <- part2(yellowDF, colorList[[3]][])
greenDF <- part2(greenDF, colorList[[4]][])
blueDF <- part2(blueDF, colorList[[5]][])
indigoDF <- part2(indigoDF, colorList[[6]][])
violetDF <- part2(violetDF, colorList[[7]][])
```


```{r}

```

